name: flutter_cache_manager
description: Generic cache manager for flutter
version: 0.1.2
author: Rene Floor <pub@renefloor.nl>
homepage: https://github.com/renefloor/flutter_cache_manager

environment:
  sdk: ">=2.1.0-dev.6.0.flutter-8a919426f0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: "^0.4.0"
  path_provider: "^0.4.0"
  synchronized: "^1.5.1"
  uuid:  "^1.0.3"
  http: "^0.12.0"
